# Generated by Django 5.2.4 on 2025-07-25 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_create_default_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['scheduled'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_schedul_8c112d_idx',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date et heure du rendez-vous'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_id',
            field=models.UUIDField(help_text='Reference vers Patient dans API Gateway'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='professional_id',
            field=models.UUIDField(help_text='Reference vers Professional dans API Gateway'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('suivi', 'Suivi'), ('examen', 'Examen')], default='consultation', max_length=50),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled'], name='appointment_schedul_7cdd3a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['type'], name='appointment_type_2d073e_idx'),
        ),
    ]
