# Generated by Django 5.2.4 on 2025-07-18 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTheme',
            fields=[
                ('theme_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('theme_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dosage', models.IntegerField()),
                ('frequency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordonance',
            fields=[
                ('ordonance_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_language', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_contact_method', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.feedbacktheme')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('professional_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.department')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.professional'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=50)),
                ('scheduled_time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
                ('message_content', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.prescription')),
            ],
            options={
                'unique_together': {('medication', 'prescription')},
            },
        ),
        migrations.CreateModel(
            name='PrescriptionOrdonance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordonance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.ordonance')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.prescription')),
            ],
            options={
                'unique_together': {('prescription', 'ordonance')},
            },
        ),
    ]
